GET http://localhost:5008/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlVzZXIiLCJzdWIiOiJVc2VyIiwianRpIjoiZGY4NzM5MDQiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDozMjUwMiIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk4IiwiaHR0cDovL2xvY2FsaG9zdDo1MDA4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA0NyJdLCJuYmYiOjE3MDc0MjQ3MDAsImV4cCI6MTcxNTIwMDcwMCwiaWF0IjoxNzA3NDI0NzAxLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.R3TyuCdNA-dL9j8Et7PJGpU1nwqydx-99IDnV89B3GU

###
GET http://localhost:5008/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlBsYXllcjEiLCJzdWIiOiJQbGF5ZXIxIiwianRpIjoiMzQwMjMyNjciLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjMyNTAyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTgiLCJodHRwOi8vbG9jYWxob3N0OjUwMDgiLCJodHRwczovL2xvY2FsaG9zdDo3MDQ3Il0sIm5iZiI6MTcwNzQyNTY4MCwiZXhwIjoxNzE1MjAxNjgwLCJpYXQiOjE3MDc0MjU2ODEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.2o5TMf4XtRVpdluKPpqYOzXv_dpM_L4qRzuXwVWT1Vg